package resetgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func GenerateResetMethods(pkgPath string, targets []ResetTarget) error {
	if len(targets) == 0 {
		return nil
	}

	genFile := filepath.Join(pkgPath, "reset.gen.go")

	var sb strings.Builder

	sb.WriteString("// Code generated by resetgen; DO NOT EDIT.\n\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", targets[0].PkgName))
	sb.WriteString("import \"time\"\n\n")

	for _, t := range targets {
		sb.WriteString(fmt.Sprintf("func (s *%s) Reset() {\n", t.Name))
		sb.WriteString("    if s == nil {\n        return\n    }\n\n")

		for _, f := range t.Fields {
			fieldName := f.Name

			switch f.Kind {
			case KindPrimitive:
				typ := strings.TrimSpace(f.Type) // убираем лишние пробелы

				if typ == "string" {
					sb.WriteString(fmt.Sprintf("    s.%s = \"\"\n", fieldName))
				} else if typ == "bool" {
					sb.WriteString(fmt.Sprintf("    s.%s = false\n", fieldName))
				} else if typ == "time.Time" {
					sb.WriteString(fmt.Sprintf("    s.%s = time.Time{}\n", fieldName))
				} else {
					// Все остальные примитивы (числа, byte, rune, complex и т.д.)
					sb.WriteString(fmt.Sprintf("    s.%s = 0\n", fieldName))
				}

			case KindSlice:
				sb.WriteString(fmt.Sprintf(" s.%s = s.%s[:0]\n", fieldName, fieldName))

			case KindMap:
				sb.WriteString(fmt.Sprintf("    clear(s.%s)\n", fieldName))

			case KindPointer:
				sb.WriteString(fmt.Sprintf("    if s.%s != nil {\n", fieldName))
				switch f.Type {
				case "*string":
					sb.WriteString(fmt.Sprintf("        *s.%s = \"\"\n", fieldName))
				case "*bool":
					sb.WriteString(fmt.Sprintf("        *s.%s = false\n", fieldName))
				case "*time.Time":
					sb.WriteString(fmt.Sprintf("        *s.%s = time.Time{}\n", fieldName))
				default:
					sb.WriteString(fmt.Sprintf("        *s.%s = 0 // числовой указатель\n", fieldName))
				}
				sb.WriteString("    }\n")

			case KindStruct:
				sb.WriteString(fmt.Sprintf("    if s.%s != nil {\n", fieldName))
				sb.WriteString(fmt.Sprintf("        if r, ok := any(s.%s).(interface{ Reset() }); ok {\n", fieldName))
				sb.WriteString("            r.Reset()\n")
				sb.WriteString("        }\n")
				sb.WriteString("    }\n")

			}
		}

		sb.WriteString("}\n\n")
	}

	content := sb.String()

	// Записываем в файл
	err := os.WriteFile(genFile, []byte(content), 0644)
	if err != nil {
		return fmt.Errorf("error writing reset.gen.go: %s", err)
	}

	fmt.Printf("Generated reset.gen.go: %s\n", genFile)
	return nil
}
