// Пакет resetgen реализует генерацию методов Reset() для Go-структур.
//
// Генератор создаёт файл reset.gen.go в каждом пакете, где найдены структуры
// с маркером //generate:reset. Сгенерированный файл содержит методы Reset()
// для всех помеченных структур, которые рекурсивно сбрасывают все поля
// в нулевые значения.
package resetgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateResetMethods генерирует файл с методами Reset() для всех структур в пакете.
//
// Функция создаёт файл reset.gen.go в директории пакета, содержащий:
//   - Метод Reset() для каждой структуры, сбрасывающий все поля
//   - Проверку на nil для безопасности
//   - Обработку различных типов полей (примитивы, слайсы, мапы, указатели, структуры)
//
// Параметры:
//   - pkgPath: полный путь к директории пакета на диске
//   - targets: список структур, для которых нужно сгенерировать методы
//
// Возвращает:
//   - error: ошибка, если генерация или запись файла не удались (nil при успехе)
//
// Алгоритм работы:
// 1. Проверяет, что есть цели для генерации (иначе завершается)
// 2. Формирует путь к выходному файлу: pkgPath/reset.gen.go
// 3. Генерирует заголовок с предупреждением о ручном редактировании
// 4. Добавляет объявление пакета и необходимые импорты
// 5. Для каждой структуры генерирует метод Reset():
//   - Проверяет получатель на nil
//   - Для каждого поля генерирует код сброса в зависимости от типа
//
// 6. Записывает полученный код в файл с правами 0644
//
// Формат генерируемого файла:
//   - Заголовок: "Code generated by resetgen; DO NOT EDIT."
//   - Пакет: тот же, что и у исходных структур
//   - Импорт: "time" (для работы с time.Time)
//   - Методы Reset() для каждой структуры
//
// Пример сгенерированного кода:
//
//	// Code generated by resetgen; DO NOT EDIT.
//
//	package models
//
//	import "time"
//
//	func (s *ShortLink) Reset() {
//	    if s == nil {
//	        return
//	    }
//
//	    s.ID = 0
//	    s.Short = ""
//	    s.Original = ""
//	    s.Clicks = 0
//	    s.CreatedAt = time.Time{}
//	    s.Tags = s.Tags[:0]
//	    clear(s.Meta)
//	}
//
// Безопасность:
//   - Все методы проверяют получатель на nil, предотвращая панику
//   - Для указателей проверяется nil перед разыменованием
//   - Для слайсов используется перезапись через [:0], сохраняющая память
func GenerateResetMethods(pkgPath string, targets []ResetTarget) error {

	// Проверяем, есть ли что генерировать
	if len(targets) == 0 {
		return nil
	}

	// Формируем путь к выходному файлу
	genFile := filepath.Join(pkgPath, "reset.gen.go")

	var sb strings.Builder

	// Заголовок с предупреждением об автоматической генерации
	sb.WriteString("// Code generated by resetgen; DO NOT EDIT.\n\n")

	// Объявление пакета (берём из первой цели, все они из одного пакета)
	sb.WriteString(fmt.Sprintf("package %s\n\n", targets[0].PkgName))

	// Импорты
	sb.WriteString("import \"time\"\n\n")

	// Генерация метода Reset() для каждой структуры
	for _, t := range targets {
		sb.WriteString(fmt.Sprintf("func (s *%s) Reset() {\n", t.Name))
		sb.WriteString("    if s == nil {\n        return\n    }\n\n")

		// Генерация кода для каждого поля в зависимости от его типа
		for _, f := range t.Fields {
			fieldName := f.Name

			switch f.Kind {
			case KindPrimitive:
				typ := strings.TrimSpace(f.Type) // убираем лишние пробелы

				// Обработка различных примитивных типов
				if typ == "string" {
					sb.WriteString(fmt.Sprintf("    s.%s = \"\"\n", fieldName))
				} else if typ == "bool" {
					sb.WriteString(fmt.Sprintf("    s.%s = false\n", fieldName))
				} else if typ == "time.Time" {
					sb.WriteString(fmt.Sprintf("    s.%s = time.Time{}\n", fieldName))
				} else {
					// Все остальные примитивы (числа, byte, rune, complex и т.д.)
					sb.WriteString(fmt.Sprintf("    s.%s = 0\n", fieldName))
				}

			case KindSlice:
				// Для слайсов используем [:0] — это очищает слайс, но сохраняет выделенную память
				// Эффективно для пулинга, так как не требует новой аллокации при следующем использовании
				sb.WriteString(fmt.Sprintf(" s.%s = s.%s[:0]\n", fieldName, fieldName))

			case KindMap:
				// Для мап используем clear() (доступно с Go 1.21)
				// clear удаляет все элементы, но сохраняет память под мапу
				sb.WriteString(fmt.Sprintf("    clear(s.%s)\n", fieldName))

			case KindPointer:
				// Для указателей проверяем nil и разыменовываем
				sb.WriteString(fmt.Sprintf("    if s.%s != nil {\n", fieldName))
				switch f.Type {
				case "*string":
					sb.WriteString(fmt.Sprintf("        *s.%s = \"\"\n", fieldName))
				case "*bool":
					sb.WriteString(fmt.Sprintf("        *s.%s = false\n", fieldName))
				case "*time.Time":
					sb.WriteString(fmt.Sprintf("        *s.%s = time.Time{}\n", fieldName))
				default:
					// Для числовых указателей
					sb.WriteString(fmt.Sprintf("        *s.%s = 0 // числовой указатель\n", fieldName))
				}
				sb.WriteString("    }\n")

			case KindStruct:
				// Для вложенных структур проверяем, реализуют ли они интерфейс Reset()
				sb.WriteString(fmt.Sprintf("    if s.%s != nil {\n", fieldName))
				sb.WriteString(fmt.Sprintf("        if r, ok := any(s.%s).(interface{ Reset() }); ok {\n", fieldName))
				sb.WriteString("            r.Reset()\n")
				sb.WriteString("        }\n")
				sb.WriteString("    }\n")

			}
		}

		sb.WriteString("}\n\n")
	}

	content := sb.String()

	// Записываем сгенерированный код в файл
	// Права 0644: владелец может читать/писать, остальные — только читать
	err := os.WriteFile(genFile, []byte(content), 0644)
	if err != nil {
		return fmt.Errorf("error writing reset.gen.go: %s", err)
	}

	fmt.Printf("Generated reset.gen.go: %s\n", genFile)
	return nil
}
